//// <auto-generated />
//using System;
//using AdminPanel.DataAccessLayer.Concrete.EntityFramework;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace AdminPanel.DataAccessLayer.Migrations
//{
//    [DbContext(typeof(EfContext))]
//    [Migration("20220621090244_jwt_tablolari")]
//    partial class jwt_tablolari
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.5")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.Araba", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<double?>("gunlukFiyat")
//                        .HasColumnType("float");

//                    b.Property<int>("kasaTipId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("markaId")
//                        .HasColumnType("int");

//                    b.Property<string>("model")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<string>("resimURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("tipId")
//                        .HasColumnType("int");

//                    b.Property<int>("uretimYili")
//                        .HasColumnType("int");

//                    b.Property<int>("vitesTipId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("kasaTipId");

//                    b.HasIndex("markaId");

//                    b.HasIndex("tipId");

//                    b.HasIndex("vitesTipId");

//                    b.ToTable("Arabalar");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaAitOzellik", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("arabaId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("ozellikId")
//                        .HasColumnType("int");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("arabaId");

//                    b.HasIndex("ozellikId");

//                    b.ToTable("ArabayaAitOzellikler");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaKasaTip", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("ArabaKasaTipleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaMarka", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("ArabaMarkalari");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaOzellik", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("ArabaOzellikleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaTip", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("ArabaTipleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaVitesTip", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("ArabaVitesTipleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.AuthenticationKismi.TokensMailPassword", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("mail")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("password")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("TokensMailPasswords");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.AuthenticationKismi.TokensTable", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<bool>("gecerlilikDurumu")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("mailPasswordId")
//                        .HasColumnType("int");

//                    b.Property<string>("refreshToken")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("refreshTokenDate")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("mailPasswordId");

//                    b.ToTable("TokensTables");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.ArabaBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("ArabaBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.GaleriBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("GaleriBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.HakkindaBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("HakkindaBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.HizmetBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("HizmetBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.IletisimBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("IletisimBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.IpucuVeYaziBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("IpucuVeYaziBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.PaketBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("PaketBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.BolumBilgileri.PersonelBolumBilgisi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("altBaslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("PersonelBolumBilgileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Bayi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("firmaId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("iletisimId")
//                        .HasColumnType("int");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("firmaId");

//                    b.HasIndex("iletisimId");

//                    b.ToTable("Bayiler");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.BayiYonetici", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("bayiId")
//                        .HasColumnType("int");

//                    b.Property<int>("firmaId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("personelId")
//                        .HasColumnType("int");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("bayiId");

//                    b.HasIndex("firmaId");

//                    b.HasIndex("personelId");

//                    b.ToTable("BayiYoneticileri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("adi")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("iletisimId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("logoURL")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("iletisimId");

//                    b.ToTable("Firmalar");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.FirmaSahip", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<int>("firmaId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("personelId")
//                        .HasColumnType("int");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("firmaId");

//                    b.HasIndex("personelId");

//                    b.ToTable("FirmaSahipleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HakkindaKismi.HakkindaIcerik", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("icerik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("resimURL")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("HakkindaIcerikleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HakkindaKismi.HakkindaReklam", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("icerik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("logoURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("HakkindaReklamlar");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.Hizmet", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("logoURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("resimURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("tanim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Hizmetler");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAlt", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("hizmetId")
//                        .HasColumnType("int");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("hizmetId");

//                    b.ToTable("HizmetAltlar");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAltOzellik", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("hizmetAltId")
//                        .HasColumnType("int");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("hizmetAltId");

//                    b.ToTable("HizmetAltOzellikler");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.IletisimKismi.Iletisim", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("adres")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("eposta")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("tel")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Iletisimleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.IpucuKismi.IpucuVeYazi", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("baslik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("icerik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("logoURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("tarih")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("IpucuVeYazilar");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.LogoKismi.SosyalMedyaLogo", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("logoURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("name")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("SosyalMedyaLogolari");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.MesajKismi.Mesaj", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("ad")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("eposta")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("icerik")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("konu")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("soyad")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Mesajlar");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.MusteriKismi.Musteri", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("ad")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("firmaId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("soyad")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("tc")
//                        .IsRequired()
//                        .HasMaxLength(11)
//                        .HasColumnType("nvarchar(11)");

//                    b.HasKey("Id");

//                    b.HasIndex("firmaId");

//                    b.ToTable("Musteriler");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.Paket", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<double>("fiyat")
//                        .HasColumnType("float");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("Paketler");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketAitOzellik", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("ozellikId")
//                        .HasColumnType("int");

//                    b.Property<int>("paketId")
//                        .HasColumnType("int");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("ozellikId");

//                    b.HasIndex("paketId");

//                    b.ToTable("PaketAitOzellikleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketOzellik", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("PaketOzellikleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("ad")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("fotoURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("soyad")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("tc")
//                        .IsRequired()
//                        .HasMaxLength(11)
//                        .HasColumnType("nvarchar(11)");

//                    b.HasKey("Id");

//                    b.ToTable("Personeller");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelGorev", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("isim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("personelId")
//                        .HasColumnType("int");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("tanim")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("personelId");

//                    b.ToTable("PersonelGorevleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSifre", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("personelId")
//                        .HasColumnType("int");

//                    b.Property<string>("sifre")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("personelId");

//                    b.ToTable("PersonelSifreleri");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSosyalMedya", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime?>("guncellemeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("kayitZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("personelId")
//                        .HasColumnType("int");

//                    b.Property<bool>("sil")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("silmeZamani")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("sosyalMedyaLogoId")
//                        .HasColumnType("int");

//                    b.Property<string>("sosyalMedyaURL")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("personelId");

//                    b.HasIndex("sosyalMedyaLogoId");

//                    b.ToTable("PersonelSosyalMedyalari");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.Araba", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaKasaTip", "kasaTip")
//                        .WithMany()
//                        .HasForeignKey("kasaTipId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaMarka", "marka")
//                        .WithMany()
//                        .HasForeignKey("markaId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaTip", "tip")
//                        .WithMany()
//                        .HasForeignKey("tipId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaVitesTip", "vitesTip")
//                        .WithMany()
//                        .HasForeignKey("vitesTipId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("kasaTip");

//                    b.Navigation("marka");

//                    b.Navigation("tip");

//                    b.Navigation("vitesTip");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaAitOzellik", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.Araba", "araba")
//                        .WithMany()
//                        .HasForeignKey("arabaId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.ArabaKismi.ArabaOzellik", "ozellik")
//                        .WithMany()
//                        .HasForeignKey("ozellikId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("araba");

//                    b.Navigation("ozellik");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.AuthenticationKismi.TokensTable", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.AuthenticationKismi.TokensMailPassword", "mailPassword")
//                        .WithMany()
//                        .HasForeignKey("mailPasswordId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("mailPassword");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Bayi", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
//                        .WithMany()
//                        .HasForeignKey("firmaId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.IletisimKismi.Iletisim", "iletisim")
//                        .WithMany()
//                        .HasForeignKey("iletisimId")
//                        .OnDelete(DeleteBehavior.ClientCascade);

//                    b.Navigation("firma");

//                    b.Navigation("iletisim");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.BayiYonetici", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Bayi", "bayi")
//                        .WithMany()
//                        .HasForeignKey("bayiId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
//                        .WithMany()
//                        .HasForeignKey("firmaId")
//                        .OnDelete(DeleteBehavior.ClientCascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
//                        .WithMany()
//                        .HasForeignKey("personelId")
//                        .OnDelete(DeleteBehavior.ClientCascade);

//                    b.Navigation("bayi");

//                    b.Navigation("firma");

//                    b.Navigation("personel");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.IletisimKismi.Iletisim", "iletisim")
//                        .WithMany()
//                        .HasForeignKey("iletisimId")
//                        .OnDelete(DeleteBehavior.ClientCascade);

//                    b.Navigation("iletisim");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.FirmaSahip", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
//                        .WithMany()
//                        .HasForeignKey("firmaId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
//                        .WithMany()
//                        .HasForeignKey("personelId")
//                        .OnDelete(DeleteBehavior.ClientCascade);

//                    b.Navigation("firma");

//                    b.Navigation("personel");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAlt", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.Hizmet", "hizmet")
//                        .WithMany()
//                        .HasForeignKey("hizmetId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("hizmet");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAltOzellik", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.HizmetKismi.HizmetAlt", "hizmetAlt")
//                        .WithMany()
//                        .HasForeignKey("hizmetAltId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("hizmetAlt");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.MusteriKismi.Musteri", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.FirmaKismi.Firma", "firma")
//                        .WithMany()
//                        .HasForeignKey("firmaId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("firma");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketAitOzellik", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.PaketOzellik", "ozellik")
//                        .WithMany()
//                        .HasForeignKey("ozellikId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PaketKismi.Paket", "paket")
//                        .WithMany()
//                        .HasForeignKey("paketId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("ozellik");

//                    b.Navigation("paket");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelGorev", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
//                        .WithMany()
//                        .HasForeignKey("personelId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("personel");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSifre", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
//                        .WithMany()
//                        .HasForeignKey("personelId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("personel");
//                });

//            modelBuilder.Entity("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.PersonelSosyalMedya", b =>
//                {
//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.PersonelKismi.Personel", "personel")
//                        .WithMany()
//                        .HasForeignKey("personelId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("AdminPanel.EntityLayer.Concrete.Other.LogoKismi.SosyalMedyaLogo", "sosyalMedyaLogo")
//                        .WithMany()
//                        .HasForeignKey("sosyalMedyaLogoId");

//                    b.Navigation("personel");

//                    b.Navigation("sosyalMedyaLogo");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
